on: # Only trigger when new release/edited/added/created/ pushed or files were edited.
  push:
    branches: ["main"]
  release:
    types:
      - created
      - published
      - edited
      - deleted
      - released

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python 3.8 # Install Python3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 
      - name: Install PiP Packages
        run:  pip install PyGithub pandas #Install Packages
      - name: Run Script
        run: |
         rm -fv *.date # Delete previously created Updated.date
         python3 generate_json.py #Run the script
         touch Updated:$(date +"%d-%m_%H:%M").date # Create Updated.date
         rm -rfv *.ipa #Can be added to .gitignore also
      - name: Configure git and Upload
        run: |
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --global user.name "github-actions[bot]" # Default actions user doesnt require Token etc.
         git add . # Add entire workspace 
         git commit -a -m "Apps updated. <Auto Action>" # Adds Message
         git push # Let's upload