name: Update-Apps

on:
  push:
    branches: ["main"]
  release:
    types:
      - created
      - published
      - edited
      - deleted
      - released

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python3 # Install Python3 
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
          check-latest: true # Always grab newest
      - name: Install pip Packages
        run:  pip install PyGithub pandas #Install pip Packages
      - name: Update Apps
        run: |
         rm -fv *.date # Delete previously created Updated.date
         python3 generate_json.py #Run the script
         touch Updated_$(date +"%d-%m_%H:%M").date # Create Updated.date
      - name: Configure git and Upload # This way no token/secret etc required.
        run: |
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --global user.name "github-actions[bot]" # Default actions user doesnt require Token etc.
         git add . # Add entire workspace 
         git commit -asn -m "Apps updated. <Auto Action>" # Adds Message
         git push --no-signed origin main --force --verbose # Let's upload